### ISSUE TITLE
nothing happen when instaling on blender 2.82

### ISSUE THREAD

**Issue by tomaszjacek** [makehumancommunity/community-plugins-maketarget#4]
Hi,

"MakeTarget2" panel doesnt appears on the N-shelf in blender

bpy.context.space_data.system_folders_active = 2
bpy.context.space_data.system_folders_active = 2
Modules Installed () from 'G:\\download\\blender\\community-plugins-maketarget-master.zip' into 'C:\\Users\\stefan\\AppData\\Roaming\\Blender Foundation\\Blender\\2.82\\scripts\\addons'
bpy.context.area.ui_type = 'INFO'

Thank you,
tj

**Comment by Aranuvir** [comment]
You have downloaded a full clone of the repo. You need to install the maketarget folder inside of the zip file. Either place it manually or zip the maketarget folde again and install it with blenders plugin installer. Purging the inoperable data from Blender's config first is advisable.
